# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import RSA


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 209)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")

        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.inputText = QtWidgets.QTextEdit(self.centralwidget)
        self.inputText.setObjectName("inputText")
        self.verticalLayout_2.addWidget(self.inputText)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)

        self.inputNOpen = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNOpen.setObjectName("inputNOpen")
        self.horizontalLayout.addWidget(self.inputNOpen)

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)

        self.inputSOpen = QtWidgets.QLineEdit(self.centralwidget)
        self.inputSOpen.setObjectName("inputSOpen")
        self.horizontalLayout.addWidget(self.inputSOpen)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)

        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)

        self.inputNClose = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNClose.setObjectName("inputNClose")
        self.horizontalLayout_2.addWidget(self.inputNClose)

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)

        self.inputEClose = QtWidgets.QLineEdit(self.centralwidget)
        self.inputEClose.setObjectName("inputEClose")
        self.horizontalLayout_2.addWidget(self.inputEClose)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)

        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)

        self.Coding = QtWidgets.QPushButton(self.centralwidget)
        self.Coding.setObjectName("Coding")
        self.Coding.clicked.connect(self.encrypt)
        self.verticalLayout_6.addWidget(self.Coding)

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)

        self.Encodig = QtWidgets.QPushButton(self.centralwidget)
        self.Encodig.setObjectName("Encodig")
        self.Encodig.clicked.connect(self.decrypt)
        self.verticalLayout_6.addWidget(self.Encodig)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.outputText = QtWidgets.QTextEdit(self.centralwidget)
        self.outputText.setObjectName("outputText")
        self.verticalLayout.addWidget(self.outputText)

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.GN = QtWidgets.QLabel(self.centralwidget)
        self.GN.setObjectName("GN")
        self.horizontalLayout_5.addWidget(self.GN)

        self.inputGenerateN = QtWidgets.QLineEdit(self.centralwidget)
        self.inputGenerateN.setObjectName("inputGenerateN")
        self.horizontalLayout_5.addWidget(self.inputGenerateN)

        self.GS = QtWidgets.QLabel(self.centralwidget)
        self.GS.setObjectName("GS")
        self.horizontalLayout_5.addWidget(self.GS)

        self.inputGenerateS = QtWidgets.QLineEdit(self.centralwidget)
        self.inputGenerateS.setObjectName("inputGenerateS")
        self.horizontalLayout_5.addWidget(self.inputGenerateS)

        self.GE = QtWidgets.QLabel(self.centralwidget)
        self.GE.setObjectName("GE")
        self.horizontalLayout_5.addWidget(self.GE)

        self.inputGenerateE = QtWidgets.QLineEdit(self.centralwidget)
        self.inputGenerateE.setObjectName("inputGenerateE")
        self.horizontalLayout_5.addWidget(self.inputGenerateE)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)

        self.GenerateButton = QtWidgets.QPushButton(self.centralwidget)
        self.GenerateButton.setObjectName("GenerateButton")
        self.GenerateButton.clicked.connect(self.Generate)
        self.horizontalLayout_6.addWidget(self.GenerateButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "                                     Текст"))
        self.label.setText(_translate("MainWindow", "открытый ключ"))
        self.label_5.setText(_translate("MainWindow", "N"))
        self.label_6.setText(_translate("MainWindow", "S"))
        self.label_4.setText(_translate("MainWindow", "закрытый ключ"))
        self.label_7.setText(_translate("MainWindow", "N"))
        self.label_8.setText(_translate("MainWindow", "e"))
        self.Coding.setText(_translate("MainWindow", "Зашифровать"))
        self.Encodig.setText(_translate("MainWindow", "Расшифровать"))
        self.label_3.setText(_translate("MainWindow", "                                 Результат"))
        self.label_11.setText(_translate("MainWindow", "Генерация ключей"))
        self.GN.setText(_translate("MainWindow", "N"))
        self.GS.setText(_translate("MainWindow", "S"))
        self.GE.setText(_translate("MainWindow", "e"))
        self.GenerateButton.setText(_translate("MainWindow", "сгенерировать"))

    def Generate(self):
        lst = RSA.rand47()
        p, q = lst[0], lst[-1]
        N, s, e = RSA.RSA(p, q)
        self.inputGenerateN.setText(str(N))
        self.inputGenerateS.setText(str(s))
        self.inputGenerateE.setText(str(e))

    def encrypt(self):
        if self.inputNOpen.text().isdigit() and self.inputSOpen.text().isdigit():
            self.outputText.setText(' '.join(
                RSA.encrypt(str(self.inputText.toPlainText()), int(self.inputNOpen.text()),
                            int(self.inputSOpen.text()))))
        else:
            self.outputText.setText("Ошибка в открытом ключе")

    def decrypt(self):
        if ''.join(str(self.inputText.toPlainText()).split()).isdigit() and self.inputNClose.text().isdigit() and \
                self.inputEClose.text().isdigit():
            print(str(self.inputText.toPlainText()))
            self.outputText.setText(''.join(
                RSA.decrypt(str(self.inputText.toPlainText()).split(), int(self.inputNClose.text()),
                            int(self.inputEClose.text()))))
        else:
            self.outputText.clear()
